AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket to EventBridge to Lambda

Parameters:
  SourceBucket:
    Type: String
  DestinationBucket:
    Type: String
  AppName:
    Description: Name of Application
    Type: String
    Default: apigw-http-api-lambda
Resources:
  # Enforce HTTPS only access to S3 bucket #
  BucketSourceForImagePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub "${SourceBucket}"
      PolicyDocument:
        Statement:
        - Action: s3:*
          Effect: Deny
          Principal: "*"
          Resource:
          - !Sub "arn:aws:s3:::${SourceBucket}/*"
          - !Sub "arn:aws:s3:::${SourceBucket}"
          Condition:
            Bool:
              aws:SecureTransport: false
  BucketDestinationForImagePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub "${DestinationBucket}"
      PolicyDocument:
        Statement:
        - Action: s3:*
          Effect: Deny
          Principal: "*"
          Resource:
          - !Sub "arn:aws:s3:::${DestinationBucket}/*"
          - !Sub "arn:aws:s3:::${DestinationBucket}"
          Condition:
            Bool:
              aws:SecureTransport: false
  ## Lambda function
  CleanFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./clean_embassy/target/lambda/clean_embassy/bootstrap
      Architectures: ["x86_64"] ## can't use arm64 in eu-west-3
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 512
      Timeout: 30
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucket
        - S3WritePolicy:
            BucketName: !Ref DestinationBucket
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.s3"
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - !Ref SourceBucket
      Tags:
        project: "serverless-embassy-locator"
        application: "backend"
      Environment:
        Variables:
          RUST_BACKTRACE: full
          RUST_LOG: info

##########################################################################
#  API Gateway HTTP API                                                  #
##########################################################################
  HttpApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Ref AppName
      Description: An Amazon API Gateway HTTP API and an AWS Lambda function.
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - POST
      Target: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FilterFunction}/invocations
      Tags:
        project: "serverless-embassy-locator"
        application: "frontend"
##########################################################################
#   Lambda Function                                                      #
##########################################################################
  FilterFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./filter_embassy/target/lambda/filter_embassy/bootstrap
      Architectures: ["x86_64"] ## can't use arm64 in eu-west-3
      # Function permissions grant an AWS service or another account permission to use a function
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 512
      Timeout: 30
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DestinationBucket
      Environment:
        Variables:
          RUST_BACKTRACE: full
          RUST_LOG: info
      Tags:
        project: "serverless-embassy-locator"
        application: "backend"
  FunctionResourcePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref FilterFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*'

Outputs:
  SourceBucketName:
    Value: !Ref SourceBucket
    Description: S3 Bucket source for object storage
  DestinationBucketName:
    Value: !Ref DestinationBucket
    Description: S3 Bucket destination for object storage
  FunctionArn:
    Value: !Ref CleanFunction
    Description: CleanFunction ARN
  HttpApiEndpoint:
    Description: The default endpoint for the HTTP API.
    Value: !GetAtt HttpApi.ApiEndpoint