AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket to EventBridge to Lambda

Parameters:
  SourceBucket:
    Type: String

Resources:
  # Enforce HTTPS only access to S3 bucket #
  BucketForImagePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub "${SourceBucket}"
      PolicyDocument:
        Statement:
        - Action: s3:*
          Effect: Deny
          Principal: "*"
          Resource:
          - !Sub "arn:aws:s3:::${SourceBucket}/*"
          - !Sub "arn:aws:s3:::${SourceBucket}"
          Condition:
            Bool:
              aws:SecureTransport: false

  ## Lambda function
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./clean_embassy/target/lambda/clean_ambassy/bootstrap
      Architectures: ["x86_64"] ## can't use arm64 in eu-west-3
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 512
      Timeout: 30
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucket
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.s3"
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - !Ref SourceBucket
      Environment:
        Variables:
          RUST_BACKTRACE: 1
          RUST_LOG: info

Outputs:
  SourceBucketName:
    Value: !Ref SourceBucket
    Description: S3 Bucket for object storage
  FunctionArn:
    Value: !Ref MyFunction
    Description: MyFunction ARN

